#! /bin/bash

[ -z $VERT_PADDING ] && export VERT_PADDING=10

#XINIT STUFF
export USB="/run/media/$(whoami)"
export WM=bspwm
export EDITOR=vim
export COMPOSITOR=picom
export TERMINAL="alacritty"
export XDG_SESSION_TYPE=x11
export LIBGL_DRI3_DISABLE=1
export FILE_MANAGER="$TERMINAL -e ranger"
export SCRIPTS_FOLDER="$HOME/.scripts"
export DMENU=1
export QT_QPA_PLATFORMTHEME=gtk2
export PATH="$HOME/.cargo/bin:$HOME/.src/Discord:$SCRIPTS_FOLDER:$S
CRIPTS_FOLDER/lemon:$SCRIPTS_FOLDER/dmenu:$HOME/.local/bin:$PATH"

[ -f $HOME/.config/x/Xresources ] && xrdb -merge $HOME/.config/x/Xresources
[ -f /etc/X11/xinit/.Xmodmap ] && xmodmap /etc/X11/xinit/.Xmodmap

#Needed for Java Apps like PyCharm
wmname LG3D

#Reads and generates all coloring from conf.yml
conf_to_script.sh &
sleep 2
xob.sh &
volumeicon &
$HOME/.fehbg &
xbanish &
dunst &
mpd &
#picom &
(sleep 1 && paplay $HOME/Sounds/startup.wav) &
pactl set-sink-volume @DEFAULT_SINK@ 50%
udiskie &
sxhkd &

#Makes sure the physical adapter for my laptop is on
command -v iwctl && iwctl adapter phy0 set-property "Powered" on

(sleep 1 && polybar -r example) &

conf () {
	yq .$1 ~/conf.yml | tr -d "'"
}

xsetroot -cursor_name left_ptr &

bspc monitor -d $(conf 'wm.tags[]')

bspc config top_padding		$(conf lemon.width)
bspc config bottom_padding	0

bspc config left_padding	0
bspc config right_padding	0

bspc config active_border_color "$(conf lemon.bordercolor)"
bspc config normal_border_color "$(conf bg)"

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Plank layer=above manage=manageborder=off
bspc rule -a Screenkey manage=off

