#!/bin/sh

userresources=$HOME/.config/x/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

while :; 
do
	[ -f $sysresources ] && xrdb -merge $sysresources
	[ -f $sysmodmap ] && xmodmap $sysmodmap
	[ -f "$userresources" ] && xrdb -merge "$userresources"
	[ -f "$usermodmap" ] && xmodmap "$usermodmap"

	$SCRIPTS_FOLDER/alacritty-w-xresources.py $HOME/.config/alacritty/alacritty.yml &
	$SCRIPTS_FOLDER/xob.sh &
	$HOME/.fehbg &
	xbanish &
	dunst &
	mpd &
	(sleep 1 && paplay $HOME/Sounds/startup.wav) &
	dbus-run-session bspwm -c $HOME/.config/bspwm/bspwmrc
done
