#!/bin/sh

userresources=$HOME/.config/x/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

while :; 
do
	[ -f $sysresources ] && xrdb -merge $sysresources
	[ -f $sysmodmap ] && xmodmap $sysmodmap
	[ -f "$userresources" ] && xrdb -merge "$userresources"
	[ -f "$usermodmap" ] && xmodmap "$usermodmap"

	$SCRIPTS_FOLDER/alacritty-w-xresources.py $HOME/.config/alacritty/alacritty.yml &
	$HOME/.fehbg &
	$SCRIPTS_FOLDER/xob.sh &
	(sleep .25 && $SCRIPTS_FOLDER/lemon/start-bar.sh) &
	xbanish &
	sxhkd &
	dunst &
	mpd &
	picom --experimental-backends &
	dbus-run-session dwm
done
