#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

$SCRIPTS_FOLDER/alacritty-w-xresources.py $HOME/.config/alacritty/alacritty.yml &
$HOME/.fehbg &
xbanish &
$SCRIPTS_FOLDER/xob.sh &
(sleep .25 && $SCRIPTS_FOLDER/lemon/lemonbartop) &
sxhkd &
dunst &
mpd &
picom --experimental-backends &
exec dbus-run-session frankenwm
