#!/bin/sh

dimensions="1920x32+0+0"
bar () { 
lemonbar -d -g $dimensions -f "Ubuntu Nerd Font:size=16" \
   -f "Ubuntu Nerd Font:size=20" -f "Ubuntu Nerd Font:size=18" \
   -F "$(xgetres a.foreground)" -B "$(xgetres a.background)" 
}

$HOME/.scripts/lemontopc | bar | bash ; exit
