#!/bin/sh

dimensions="1920x32+0+0"
bar () { 
  lemonbar -d -g $dimensions -u 2 -f "$(xgetres lemon.font1)" -o $(xgetres lemon.font1.offset) \
   -f "$(xgetres lemon.font2)" -o $(xgetres lemon.font2.offset) -f "$(xgetres lemon.font3)" -o $(xgetres lemon.font3.offset) \
   -F "$(xgetres a.foreground)" -B "$(xgetres a.background)" \
   -U $(xgetres a.foreground) -a 20
}

#WIP - trying to prevent _NET_DESKTOP_NAMES:notfound bar
xprop -root _NET_DESKTOP_NAMES > /dev/null 2>/dev/null
while [ $? -eq 1 ]; do
  sleep 1
  xprop -root > /dev/null 2>/dev/null
done

$SCRIPTS_FOLDER/lemon/lemontopc | tee $HOME/.lemlog | bar | bash ; exit
