all:
	gcc lemon.top.c -o lemontopc
	gcc lemon.bottom.c -o lemonbottomc
main:
	gcc lemon.top.c -o lemontopc -DMAIN
secondary:
	gcc lemon.top.c -o lemonbottomc -DSECONDARY
one:
	gcc lemon.top.c -o lemontopc  -DONE
